feat: ajout de mes socials-raveliop
gdscuy1/socials pull request #12
Opened 2023-10-14 14:45 UTC by Raveliop

nouvelle modif

2023-10-14 14:48 UTC, Joel-Fah requested changes

2023-10-14 14:48 UTC, Joel-Fah commented on archives/2023/raveliop.json
> +
Retire les espaces vides que tu as laissé à ce niveau.

2023-10-15 14:09 UTC, Raveliop commented
nouvelle modif 2

2023-10-15 14:38 UTC, Joel-Fah approved these changes

2023-10-15 14:39 UTC, merged